### ISSUE TITLE
Options for a manifest

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dctap#16]
The primer needs a short section (probably as part of the appendix) given some options that we see for the creation of a manifest that can provide additional information about the profile. Some possible data for the manifest:

* Administrative data (who created the profile, when, etc.)
* Overriding of boolean defaults from 1/0, true/false
* ?? other

What we need for this issue is to develop the wording for that section.

**Comment by philbarker** [comment]
* ++ alternative column headings

**Comment by bencomp** [comment]
Would it help to base such a manifest on the [CSV on the Web metadata](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/) JSON file? That covers alternative column headings.

**Comment by kcoyle** [comment]
I do think that we should have the CSV on the web JSON as one of the options. Can anyone here mock that up?

**Comment by philbarker** [comment]
@kcoyle will do.

**Comment by kcoyle** [comment]
@philbarker Thanks, Phil. Also, take a look at the [example](https://github.com/dcmi/dctap/issues/3#issuecomment-789652864) that Nishad did on #3. He based on that CSVW but used a table format for the data. Perhaps these two could be somewhat parallel to show both methods?

**Comment by kcoyle** [comment]
@bencomp Thanks. We are looking at CSV on the Web for this, among other solutions, but are also wanting to develop a table-based option (since CSVW uses Json). We figure that we will present multiple options as examples of how one might encode a manifest. Note that the only aspect of a manifest that seems to be absolutely necessary for TAP is the definition of prefixes to used namespaces. This means that we'll probably have a range of examples beyond that single requirement, but may not specify a single TAP manifest.

**Comment by bencomp** [comment]
@kcoyle Thanks, I just arrived at this repository and had missed the extensive mentions of CSVW in #3.
If I understand correctly, an *[application] profile* is a way of expressing what makes a *resource description* valid. The *manifest* aims to minimally prescribe the mappings for translating [CURIEs][curie] to IRIs and (optionally) describe the *profile*.

If the *resource description* were expressed in RDF (whatever the serialisation), I would look at SHACL (or ShEx) to define the valid shapes. The SHACL would serve as the *profile*. To describe the *profile*, i.e. collection of SHACL shapes, I would again use RDF and it could go in the same file as the SHACL or it could be a separate resource. I think all RDF serialisations have ways of mapping CURIEs to IRIs, so that question would not be an issue.

If the *profile* were expressed in CSV and I wanted to interpret the values as RDF to validate RDF *resource descriptions*, I would want to convert the CSV to SHACL or ShEx. Several conversions exist, including CSV on the Web metadata (CSVM) and [RML]. Both CSVM and RML are expressed in RDF, so they could include the *manifest*.
I think in a CSVM file you could specify a column's `datatype` to be `{ "@id": "http://www.w3.org/1999/xhtml/datatypes/CURIE" }` to indicate its values are CURIEs, but I don't expect existing processors to understand what to do with that. TAP processors could be made aware and instructed to convert CURIEs to IRIs using, e.g., the mappings in the `@context` in the CSVM.

All I really wanted to say is: are you sure you're not reinventing the wheel? CSVM ticks all the boxes for the list at the top:

* [documenting the CSV/TAP](https://www.w3.org/TR/2016/NOTE-tabular-data-primer-20160225/#documentation)
* [overriding boolean values](https://www.w3.org/TR/2016/NOTE-tabular-data-primer-20160225/#boolean-format)
* [alternative column headings](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#columns)

And more:

* [detailed instructions for parsing CSVs](https://www.w3.org/TR/tabular-data-model/#processing-tables) – though I understand from the discussion in #26 that there may be a specific way to read CSV files
* [ways of connecting the *manifest* to the CSV](https://www.w3.org/TR/tabular-data-model/#locating-metadata) (#17, mentioned in https://github.com/dcmi/dctap/issues/3#issuecomment-830608470)
* [expressing that values in cells are ordered](https://www.w3.org/TR/2016/NOTE-tabular-data-primer-20160225/#list-values) (#14)

If you definitely want to express the *manifest* as CSV to use as rules for validating the CSV *profile*, you're doing something that I haven't seen before. That doesn't mean it shouldn't be done, of course. You could reverse engineer the CSVM vocabulary to fit in CSV and provide a default mapping to RDF (I'd suggest to make it a CSVM file), along with instructions to derive your own CSVM file. A disadvantage of using CSV for elaborate schemas is that you could end up with

* a table with lots of well-defined columns and many empty cells,
* or the manifest split into several tables that need to reference one another,
* or one table with no empty cells, but very generic columns that start to look like `subject,predicate,object` so that it can hold any data.

I don't want to suggest that every issue has been solved already, but I do see some overlap with existing standards and initiatives and hope that these are considered when looking for solutions for TAPs.

[curie]: https://www.w3.org/TR/curie/
[RML]: https://rml.io/

**Comment by kcoyle** [comment]
@bencomp Thanks for your detailed comment. It inspired me to spend the weekend doing a close reading of the CSVW documents. There is, as you mention, the *meta* problem: CSVW is for *data* in tabular format, and TAP is a tabular format for a profile describing metadata choices for metadata in *any* format. It's the profile that is tabular, so CSVW would only apply to the profile itself. I believe that this means that there will be *some* features of CSVW that we might use, but others may not be appropriate. For example, the CSVW `ordered` values in cells will only apply to tabular data; the request in #14 was to designate the order of *property/value pairs* in the RDF metadata the TAP defines. Order of values in cells in a TAP is probably an edge case (I can't think of an example where this would be needed).

We should definitely look at CSVW to see what it can offer for some functions:
* admin data
* connecting a manifest to a TAP
* allowing multiple TAP modules to co-exist and be combined
* defining prefixes to URIs
* giving alternate titles for columns

(Note, I haven't found a way to provide alternate text for booleans in CSVW - would appreciate a tip for that.)

There may be other features as well. However, it looks to me that CSVW is quite a bit more complex than we want to embrace for the small number of needs we have. For example, it isn't clear to me if a CSVW description of the [TAP vocabulary](https://github.com/dcmi/dctap/blob/main/TAPvocabulary.md) would be useful. It would define basic validation for created TAP columns but we've been leaving things pretty loose so I'm not sure how much validation of that type is needed. Each created TAP would need a different CSVW file to solve our needs, and that is more complicated than we've embraced so far with TAP. Of course, anyone who has the skills and wants to create a CSVW annotation for their TAP is welcome to do so.

Ideally, the manifest would be something very simple that people could encode in a spreadsheet, and that would be transformed to a more usable format by the program that ingests the CSV.

**Comment by philbarker** [comment]
@kcoyle wrote:

> (Note, I haven't found a way to provide alternate text for booleans in CSVW - would appreciate a tip for that.)

It's here https://www.w3.org/TR/tabular-data-primer/#boolean-format

**Comment by kcoyle** [comment]
*This is Nishad's suggestion, from #3*

I liked the tabular way of expressing prefixes proposed by Karen, not so sure if we need to use a prefixed header for that. Probably the ontology is the best place to include any such mapping.

CSVW proposes a JSON metadata file relative to the path of the CSV, something like `path/file.csv-metadata.json` 

Other than declaring prefixes, as per the DCAP Guidelines [1] 5.1 encourages declaring a set of metadata for the application profiles. 

Not as a proposal, but I am curious if both of these can be implemented in a tabular format, as we are primarily focusing our interests on a tabular representation of application profiles.

The following is not a proposal but exploring the possibilities for discussing such a metadata file in tabular format. Headers are fictional, used as an example.

A metadata file with prefixes for the DCTAP `path/foo-dctap.csv` can be `path/foo-dctap.csv-metadata.csv`. Which can be :

| MetadataID | MetadataType | Value | Notes |
|:--|:--|:--|:--|
| dct | Namespace | http://purl.org/dc/terms/ | DublinCore Terms |
| schema | Namespace | http://schema.org/ | Schema.org |
| dcat | Namespace | http://www.w3.org/ns/dcat# | DCAT Vocabulary |
| dct:title | LITERAL | Foo Application Profile | |
| dct:creator | IRI | 	https://orcid.org/0000-0000-1111-0000 | |
| dct:creator | IRI | 	https://orcid.org/0000-0000-1111-1111 | |
| dct:contributor | IRI | 	https://orcid.org/0000-0000-1111-2222 | |
| dct:license | IRI | https://opendatacommons.org/licenses/odbl/1.0/ | |
| dct:description | LITERAL | A human readable description | |
| dcat:downloadURL| IRI | https://zenodo.org/record/xxxx/files/xxx/data-v1.0.0.zip?download=1| |
| dcat:distribution| IRI | https://doi.org/10.5281/zenodo.xxxx| |

[1] https://www.dublincore.org/specifications/dublin-core/application-profile-guidelines/

**Comment by kcoyle** [comment]
*I also tried to create a table and did a myriad of different versions, none of which seemed to work.*

There seem to be 5 different kinds of data statements we need to make:
1. Link to the TAP file
1. URIs and their prefixes
2. admin data about the table
3. alternate column header displays
4. alternate values for Boolean columns

It isn't easy getting these all into one table. Nishad covered 1 and 2. My table below tries to cover them all. Note that in my table 
* the URI is the ID and the prefix is a value on the row
* the link to the TAP file is the ID for the table admin data
* the ID to the column header is the TAP property
* I don't think the way Boolean options are shown here is very good

|ID|property|datatype|prefix|display options|Boolean|
|----|----|----|----|----|----|
|http://purl.org/dc/terms/|||dct||
|http://schema.org/|||sdo||
|http://www.w3.org/2001/XMLSchema#|||xsd||
|:MyTap123|dc:title|xsd:string|||
|:MyTap123|dc:publisher|xsd:string|||
|:MyTap123|dc:modified|xsd:date|||
|tap:shapeID||rdf:langString||“entity”@en “entità”@it|
|tap:propertyID||rdf:langString||“property”@en “propriété”@fr|
|tap:mandatory||rdf:langString|||“yes/no”@en “oui/non”@fr|

**Comment by kcoyle** [comment]
Note: if we like having the URI in the ID column and the prefix in a later column in the row, we might want to also reverse these in our "prefixes only" [solution](https://github.com/dcmi/dctap/issues/3#issuecomment-785246141), and also use the same column headers (whatever they turn out to be).

**Comment by nishad** [comment]
Here is an almost equivalent YAML representation of @philbarker's [JSON-LD](https://github.com/dcmi/dctap/issues/16#issuecomment-836837419) manifest. 

```yaml
# DCTAP Manifest

prefixes:
  dc: 'http://purl.org/dc/elements/1.1/'
  rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#'
  xsd: 'http://www.w3.org/2001/XMLSchema#'
  ceterms: 'https://purl.org/ctdl/terms/'
  agentSector: 'https://purl.org/ctdl/vocabs/agentSector/'

metadata:
  'dc:title': Credential Engine Registry Application Profile
  'dc:description': Describes the minimum data policy for publishing to the Credential Engine Registry
  'dc:creator': https://credentialengineregistry.org/resources/ce-9bd8c615-9f3c-40e6-9c20-6d9f811844e6

tableSchema:
  columns:
    - name: shapeID
      title:
        en: Shape ID
        es: ID de Forma
      datatype: anyURI
    - name: propertyID
      title:
        en: Property ID
        es: ID de properdad
      datatype: anyURI
    - name: propertyLabel
      title:
        en: Property Label
        es: Etiqueta de properdad
      datatype: string
    - name: madatory
      title:
        en: Mandatory
        es: Obligatoria
      datatype:
        base: boolean
        format: Yes|No
    - name: repeatable
      title:
        en: Repeatable
        es: Repetible
      datatype:
        base: boolean
        format: Yes|No
    - name: valueNodeType
      title:
        en: Value node type
        es: Tipo de nodo
      datatype:
        base: string
        format: IRI|Literal|BNODE
    - name: valueDataType
      title:
        en: Value data type
        es: Tipo de datos
      datatype: anyURI
    - name: valueConstraint
      title:
        en: Value constraint
        es: Restricción para valores
      datatype: string
    - name: valueConstraintType
      title:
        en: Value constraint type
        es: Tipo de restricción
      datatype: string
    - name: valueShape
      title:
        en: Value shape
        es: Forma para valores
      datatype: string
    - name: note
      title:
        en: Notes
        es: Anotaciones
      datatype: string

tables:
  - url: 'http://example.org/CE_CredentialOrg_required.csv'
    'dc:title': Required properties of a Credential Organization
  - url: 'http://example.org/CE_CredentialOrg_recommended.csv'
    'dc:title': Recommended properties of a Credential Organization
  - url: 'http://example.org/CE_Credential_required.csv'
    'dc:title': Required properties of a Credential
  - url: 'http://example.org/CE_Credential_recommended.csv'
    'dc:title': Recommended properties of a Credential

---
```
